version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - elogika-sqlserverdata:/var/opt/mssql

volumes:
  elogika-sqlserverdata:
